name: Playwright E2E Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Run Playwright tests
      run: npm run e2e
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
